### ISSUE TITLE
Update 'Contributing' section of ReadMe

### ISSUE THREAD

**Issue by raccodee** [MaksiRose/paw-and-paper#295]
Hi! I was browsing through help wanted and I found this little project and instantly loved it. I opened and read it but I’m not able to find the species file (for adding another one) which is mentioned in the README.

Will probably do some contributions if you don’t mind, I always wanted to do something similar to this :D 

Cheers!

**Comment by MaksiRose** [comment]
@raccodee That sounds lovely, thank you! The file is under utils/itemsInfo.js (since it also holds information about other items, not just species). Thank you ☺️

**Comment by raccodee** [comment]
Great! Thanks, such a good work so far 😁

**Comment by raccodee** [comment]
Btw @MaksiRose can I have some address where I can message you some short questions about the project if it's ok? You can email me or something? Thanks, sorry to bother 😅

**Comment by MaksiRose** [comment]
@raccodee you could add me on discord (maksi#8022) if you have that (i assume so)!
