### ISSUE TITLE
Bird

### ISSUE THREAD

**Issue by Spring-Wolf** [MaksiRose/paw-and-paper#379]
### What is the name of the species?

Bird

### What diet does the species have?

omnivore

### What habitat does the species live in?

warm (shrubland, savanna, desert)

### What prey does this species eat or hunt?

Depends on the type of bird

### What predators eat or hunt this species?

Depends on the type of bird

### Sources

1. asasas
2. 
3.

**Comment by MaksiRose** [comment]
@Spring-Wolf "Bird" is sadly too broad and cannot be accepted. Birds such as owls, eagles etc already exist. If you want a specific bird added to the bot, please open another Species request about that bird type. Prey, predators and sources are required. If you see that your answer is that it "depends", you may be more specific with the type of bird you would like to see added.

Thanks for your contribution!
