### ISSUE TITLE
New species: 

### ISSUE THREAD

**Issue by relaxingOcean** [MaksiRose/paw-and-paper#551]
### What is the name of the species?

Water Dragon

### What diet does the species have?

omnivore

### What habitat does the species live in?

water (river, coral reef, ocean)

### What prey does this species eat or hunt?

Humans, cows, sheep, squid, sharks, fish, etc.

### What predators eat or hunt this species?

Any that try to attack.

### Sources

No websites included.

**Comment by MaksiRose** [comment]
Hey @WaterjetTheSeaWing, I am not sure if with „Water Dragon“ you mean the mythical creature or the lizard. If you mean the mythical creature, I‘m sorry to inform you that mythical creatures won‘t be added to the list of species. If you are referring to the lizard, please make sure to edit your message above to include predators, as well as some credible sources, and to ping me in a reply so I am aware of the update. Thank you ☺️!

**Comment by MaksiRose** [comment]
If you have more questions, you can also add me on Discord: maksi#8022 ☺️
