### ISSUE TITLE
Bot is offline as soon as added

### ISSUE THREAD

**Issue by The-Professor123** [MaksiRose/paw-and-paper#671]
### Current behavior

it just sits and is offline. it doesn't do any commands either

### Expected behavior

to function i guess?

### Steps to reproduce the behavior

im new to discord server management i don't know if its me or the bot ;w;

**Comment by MaksiRose** [comment]
@The-Professor123 Thanks for your ticket. The bot is now online again.
Tip: You can join our support server (https://discord.gg/9DENgj8q5Q) and make a post there instead. This will be much faster for you and easier to manage for me :)
