### ISSUE TITLE
New species: Gila Monster

### ISSUE THREAD

**Issue by NuggetEntolodont** [MaksiRose/paw-and-paper#684]
### What is the name of the species?

Gila Monster

### What diet does the species have?

carnivore

### What habitat does the species live in?

warm (shrubland, savanna, desert)

### What prey does this species eat or hunt?

small birds, small mammals, frogs, smaller lizards, insects, bird and reptile eggs and carrion

### What predators eat or hunt this species?

coyotes
birds of prey - such as eagles and hawks
foxes
mountain lions

### Sources

1. animalia.bio
2. everythingreptilion.com

**Comment by MaksiRose** [comment]
@NuggetEntolodont Please make sure to make your sources clickable links to specific sites that you references rather than general websites!
