### ISSUE TITLE
New species: Dragonborn

### ISSUE THREAD

**Issue by ghost** [MaksiRose/paw-and-paper#819]
### What is the name of the species?

Dragonborn

### What diet does the species have?

omnivore

### What habitat does the species live in?

warm (shrubland, savanna, desert)

### What prey does this species eat or hunt?

It’s from DnD. If that’s allowed

### What predators eat or hunt this species?

None

### Sources

Google
Wikipedia
DnD beyond

**Comment by MaksiRose** [comment]
does not follow the guidelines
